try:
    printas('')
except Exception as err:
    print(err)
print('继续执行')